const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  const stockCards = [
    // Outlet 1 (OUTL0001)
    {
      id: "STK0001",
      outlet_id: "OUTL0001",
      item_id: "ITM0023",
      transaction_id: "REC0001",
      stock_in: 0,
      stock_out: 0,
      current_stock: 0,
      transaction_type: "initial_stock",
    },
    {
      id: "STK0002",
      outlet_id: "OUTL0001",
      item_id: "ITM0023",
      transaction_id: "REC0001",
      stock_in: 0,
      stock_out: 0,
      current_stock: 0,
      transaction_type: "initial_stock",
    },
    {
      id: "STK0003",
      outlet_id: "OUTL0001",
      item_id: "ITM0023",
      transaction_id: "REC0001",
      stock_in: 100,
      stock_out: 0,
      current_stock: 100,
      transaction_type: "receipt",
    },
    {
      id: "STK0004",
      outlet_id: "OUTL0001",
      item_id: "ITM0023",
      transaction_id: "REC0001",
      stock_in: 200,
      stock_out: 0,
      current_stock: 200,
      transaction_type: "receipt",
    },
    {
      id: "STK0005",
      outlet_id: "OUTL0001",
      item_id: "ITM0023",
      transaction_id: "REC0001",
      stock_in: 0,
      stock_out: 50,
      current_stock: 50,
      transaction_type: "sales",
    },
    {
      id: "STK0006",
      outlet_id: "OUTL0001",
      item_id: "ITM0023",
      transaction_id: "REC0001",
      stock_in: 0,
      stock_out: 100,
      current_stock: 100,
      transaction_type: "sales",
    },
    {
      id: "STK0007",
      outlet_id: "OUTL0001",
      item_id: "ITM0023",
      transaction_id: "REC0001",
      stock_in: 150,
      stock_out: 0,
      current_stock: 150,
      transaction_type: "receipt",
    },
    {
      id: "STK0008",
      outlet_id: "OUTL0001",
      item_id: "ITM0011",
      transaction_id: "REC0001",
      stock_in: 0,
      stock_out: 70,
      current_stock: 80,
      transaction_type: "sales",
    },
    {
      id: "STK0009",
      outlet_id: "OUTL0001",
      item_id: "ITM0011",
      transaction_id: "REC0001",
      stock_in: 120,
      stock_out: 0,
      current_stock: 120,
      transaction_type: "receipt",
    },
    {
      id: "STK0010",
      outlet_id: "OUTL0001",
      item_id: "ITM0011",
      transaction_id: "REC0001",
      stock_in: 0,
      stock_out: 90,
      current_stock: 100,
      transaction_type: "sales",
    },

    {
      id: "STK0021",
      outlet_id: "OUTL0001",
      item_id: "ITM0011",
      transaction_id: "REC0001",
      stock_in: 0,
      stock_out: 0,
      current_stock: 0,
      transaction_type: "initial_stock",
    },
    {
      id: "STK0022",
      outlet_id: "OUTL0001",
      item_id: "ITM0011",
      transaction_id: "REC0001",
      stock_in: 0,
      stock_out: 0,
      current_stock: 0,
      transaction_type: "initial_stock",
    },
    {
      id: "STK0023",
      outlet_id: "OUTL0001",
      item_id: "ITM0011",
      transaction_id: "REC0001",
      stock_in: 100,
      stock_out: 0,
      current_stock: 100,
      transaction_type: "receipt",
    },
    {
      id: "STK0024",
      outlet_id: "OUTL0001",
      item_id: "ITM0011",
      transaction_id: "REC0001",
      stock_in: 200,
      stock_out: 0,
      current_stock: 200,
      transaction_type: "receipt",
    },
    {
      id: "STK0025",
      outlet_id: "OUTL0001",
      item_id: "ITM0011",
      transaction_id: "REC0001",
      stock_in: 0,
      stock_out: 50,
      current_stock: 50,
      transaction_type: "sales",
    },
    {
      id: "STK0026",
      outlet_id: "OUTL0001",
      item_id: "ITM0011",
      transaction_id: "REC0001",
      stock_in: 0,
      stock_out: 100,
      current_stock: 100,
      transaction_type: "sales",
    },
    {
      id: "STK0027",
      outlet_id: "OUTL0001",
      item_id: "ITM0011",
      transaction_id: "REC0001",
      stock_in: 150,
      stock_out: 0,
      current_stock: 150,
      transaction_type: "receipt",
    },
    {
      id: "STK0028",
      outlet_id: "OUTL0001",
      item_id: "ITM0011",
      transaction_id: "REC0001",
      stock_in: 0,
      stock_out: 70,
      current_stock: 80,
      transaction_type: "sales",
    },
    {
      id: "STK0029",
      outlet_id: "OUTL0001",
      item_id: "ITM0011",
      transaction_id: "REC0001",
      stock_in: 120,
      stock_out: 0,
      current_stock: 120,
      transaction_type: "receipt",
    },
    {
      id: "STK0030",
      outlet_id: "OUTL0001",
      item_id: "ITM0011",
      transaction_id: "REC0001",
      stock_in: 0,
      stock_out: 90,
      current_stock: 100,
      transaction_type: "sales",
    },
  ];

  await prisma.stock_cards.createMany({
    data: stockCards,
  });

  console.log("Stock cards seeded successfully.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
